name: Deploy to DINF

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DINF_HOST }}
          username: ${{ secrets.DINF_USERNAME }}
          password: ${{ secrets.DINF_PASSWORD }}
          port: ${{ secrets.DINF_PORT }}
          script: |
            mkdir -p ~/temp_deploy
            rm -rf ~/temp_deploy/*

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DINF_HOST }}
          username: ${{ secrets.DINF_USERNAME }}
          password: ${{ secrets.DINF_PASSWORD }}
          port: ${{ secrets.DINF_PORT }}
          source: "index.html,styles.css,script.js,locales/**,pesquisa-redes-sociais/**,projetos/**"
          target: "~/temp_deploy"
          strip_components: 0

      - name: Move files and fix permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DINF_HOST }}
          username: ${{ secrets.DINF_USERNAME }}
          password: ${{ secrets.DINF_PASSWORD }}
          port: ${{ secrets.DINF_PORT }}
          script: |
            mv ~/temp_deploy/* /home/html/inf/$USER/
            chmod -R g=rX,o=rX /home/html/inf/$USER
            rm -rf ~/temp_deploy
